<a href="https://colab.research.google.com/github/vishisht-gupta/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import os
import sys
import subprocess
IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/vishisht-gupta/flyrank-ml-internship"
REPO_DIR = "flyrank-ml-internship"
if IN_COLAB:
    if not os.path.isdir(REPO_DIR):
        subprocess.run(
            ["git", "clone", "--depth", "1", REPO_URL, REPO_DIR],
            check=True
        )
    os.chdir(REPO_DIR)
print("Working Directory:", os.getcwd())

Working Directory: /content/flyrank-ml-internship

In [5]:
from google.colab import userdata
from huggingface_hub import login

hf_token = userdata.get("internship")

login(token=hf_token)

print("Logged into Hugging Face")

Logged into Hugging Face

In [6]:
from huggingface_hub import list_repo_files

files = list_repo_files(
    repo_id="FlyRank/internship-warehouse",
    repo_type="dataset"
)
print("Number of files:", len(files))
for f in files:
    print(f)

Number of files: 24
.gitattributes
README.md
dim_clients.parquet
dim_content.parquet
fact_content_daily_performance/month=2025-01/data_0.parquet
fact_content_daily_performance/month=2025-02/data_0.parquet
fact_content_daily_performance/month=2025-03/data_0.parquet
fact_content_daily_performance/month=2025-04/data_0.parquet
fact_content_daily_performance/month=2025-05/data_0.parquet
fact_content_daily_performance/month=2025-06/data_0.parquet
fact_content_daily_performance/month=2025-07/data_0.parquet
fact_content_daily_performance/month=2025-08/data_0.parquet
fact_content_daily_performance/month=2025-09/data_0.parquet
fact_content_daily_performance/month=2025-10/data_0.parquet
fact_content_daily_performance/month=2025-11/data_0.parquet
fact_content_daily_performance/month=2025-12/data_0.parquet
fact_content_daily_performance/month=2026-01/data_0.parquet
fact_content_daily_performance/month=2026-02/data_0.parquet
fact_content_daily_performance/month=2026-03/data_0.parquet
fact_content_daily_performance/month=2026-04/data_0.parquet
fact_content_daily_performance/month=2026-05/data_0.parquet
fact_content_daily_performance/month=2026-06/data_0.parquet
fact_content_daily_performance_sample.parquet
fact_content_query_90d.parquet

In [7]:
print(files)

['.gitattributes', 'README.md', 'dim_clients.parquet', 'dim_content.parquet', 'fact_content_daily_performance/month=2025-01/data_0.parquet', 'fact_content_daily_performance/month=2025-02/data_0.parquet', 'fact_content_daily_performance/month=2025-03/data_0.parquet', 'fact_content_daily_performance/month=2025-04/data_0.parquet', 'fact_content_daily_performance/month=2025-05/data_0.parquet', 'fact_content_daily_performance/month=2025-06/data_0.parquet', 'fact_content_daily_performance/month=2025-07/data_0.parquet', 'fact_content_daily_performance/month=2025-08/data_0.parquet', 'fact_content_daily_performance/month=2025-09/data_0.parquet', 'fact_content_daily_performance/month=2025-10/data_0.parquet', 'fact_content_daily_performance/month=2025-11/data_0.parquet', 'fact_content_daily_performance/month=2025-12/data_0.parquet', 'fact_content_daily_performance/month=2026-01/data_0.parquet', 'fact_content_daily_performance/month=2026-02/data_0.parquet', 'fact_content_daily_performance/month=2026-03/data_0.parquet', 'fact_content_daily_performance/month=2026-04/data_0.parquet', 'fact_content_daily_performance/month=2026-05/data_0.parquet', 'fact_content_daily_performance/month=2026-06/data_0.parquet', 'fact_content_daily_performance_sample.parquet', 'fact_content_query_90d.parquet']

In [10]:
from huggingface_hub import hf_hub_download
from google.colab import userdata

token = userdata.get("internship")

march_file = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    repo_type="dataset",
    filename="fact_content_daily_performance/month=2026-03/data_0.parquet",
    token=token
)
print(march_file)

/root/.cache/huggingface/hub/datasets--FlyRank--internship-warehouse/snapshots/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/fact_content_daily_performance/month=2026-03/data_0.parquet

In [11]:
import duckdb
con = duckdb.connect()
df = con.execute(f"""
SELECT *
FROM read_parquet('{march_file}')
LIMIT 5
""").df()
df.head()

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,<NA>,20,0,67,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,<NA>,1,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,<NA>,125,1,616,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,<NA>,7,0,28,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,<NA>,11,0,25,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03

In [12]:
print(df.columns.tolist())

['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events', 'month']

 1. My Data Contract

One row represents:
One content page for one client on one reporting date.

Tables used:
fact_content_daily_performance (March 2026)

Time window:
March 2026

Prediction / Ranking Goal:
Rank content pages that are most likely to need optimization based on historical engagement and search metrics.

Excluded Information:
Future information and any label-derived columns are excluded to avoid data leakage.

In [13]:
con.execute(f"""
SELECT COUNT(*) AS total_rows
FROM read_parquet('{march_file}')
""").df()

   total_rows
0     9841378

In [14]:
con.execute(f"""
SELECT
MIN(report_date) AS first_date,
MAX(report_date) AS last_date
FROM read_parquet('{march_file}')
""").df()

  first_date  last_date
0 2026-03-01 2026-03-31

In [15]:
con.execute(f"""
SELECT
COUNT(*) AS rows_available
FROM read_parquet('{march_file}')
WHERE gsc_data_available IS TRUE
""").df()

   rows_available
0         3611061

In [17]:
features = con.execute(f"""
SELECT
content_hash_id,
gsc_impressions,
gsc_clicks,
gsc_avg_position,
ga4_pageviews,
ga4_engaged_sessions
FROM read_parquet('{march_file}')
LIMIT 10
""").df()
features

,content_hash_id,gsc_impressions,gsc_clicks,gsc_avg_position,ga4_pageviews,ga4_engaged_sessions
0,content_b7e512995f79d5a6,20,0,3.350000,<NA>,<NA>
1,content_05597932fe4da067,1,0,0.000000,<NA>,<NA>
2,content_7a105f548d9c6916,125,1,4.928000,<NA>,<NA>
3,content_905aa32a0230694e,7,0,4.000000,<NA>,<NA>
4,content_a3ea9792f793ec72,11,0,2.272727,<NA>,<NA>
5,content_36c36abc7650d7af,239,1,7.347280,<NA>,<NA>
6,content_a7da352b73b02668,191,0,7.832461,<NA>,<NA>
7,content_05434271b257bb68,55,0,3.272727,<NA>,<NA>
8,content_d056587ff7faca0c,77,0,5.636364,<NA>,<NA>
9,content_bfd1e41c2af250c8,2,0,4.500000,<NA>,<NA>

Feature Availability

gsc_impressions
Available immediately from Google Search Console.

gsc_clicks
Known before making any optimization decision.

 gsc_avg_position
Observed search ranking before optimization.

ga4_pageviews
Collected from Google Analytics before decision time.

ga4_engaged_sessions
Represents user engagement already observed before prediction.

In [19]:
import pandas as pd

demo = features.copy()
demo["high_clicks"] = (demo["gsc_clicks"] > demo["gsc_clicks"].median()).astype(int)
demo["leaky_feature"] = demo["high_clicks"]

print(demo.head())

            content_hash_id  gsc_impressions  gsc_clicks  gsc_avg_position  \
0  content_b7e512995f79d5a6               20           0          3.350000
1  content_05597932fe4da067                1           0          0.000000
2  content_7a105f548d9c6916              125           1          4.928000
3  content_905aa32a0230694e                7           0          4.000000
4  content_a3ea9792f793ec72               11           0          2.272727

   ga4_pageviews  ga4_engaged_sessions  high_clicks  leaky_feature
0           <NA>                  <NA>            0              0
1           <NA>                  <NA>            0              0
2           <NA>                  <NA>            1              1
3           <NA>                  <NA>            0              0
4           <NA>                  <NA>            0              0

Leakage Experiment

I intentionally created `leaky_feature` directly from the target (`high_clicks`).

If this feature were used for training, the model would achieve unrealistically high performance because it already contains the answer.

After demonstrating the issue, I removed the leaky feature and kept only historical features available before the prediction time.

Limitation

This notebook uses only one month (March 2026) of warehouse data.
Seasonal trends and long-term behavior cannot be captured using a single month.

In [18]:
df.head()

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,<NA>,20,0,67,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,<NA>,1,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,<NA>,125,1,616,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,<NA>,7,0,28,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,<NA>,11,0,25,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03